spring.datasource.url=jdbc:mysql://localhost:3306/socialdb
spring.datasource.username=root
spring.datasource.password=9450390189

//autoupdate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true       